// Mirror of the backend permission keys (server/src/constants.ts).
export const P = {
  STOCK_VIEW: 'stock:view',
  STOCK_IN: 'stock:in',
  STOCK_OUT_SALE: 'stock:out_sale',
  RETURN: 'stock:return',
  TRANSFER: 'stock:transfer',
  ADJUSTMENT_REQUEST: 'adjustment:request',
  ADJUSTMENT_APPROVE: 'adjustment:approve',
  OPNAME_MANAGE: 'opname:manage',
  OPNAME_APPROVE: 'opname:approve',
  PRODUCT_MANAGE: 'product:manage',
  SUPPLIER_MANAGE: 'supplier:manage',
  LOCATION_MANAGE: 'location:manage',
  PO_MANAGE: 'po:manage',
  USERS_MANAGE: 'users:manage',
  REPORTS_VIEW: 'reports:view',
  FINANCIAL_VIEW: 'financial:view',
  AUDIT_VIEW: 'audit:view',
} as const;
